/* Generated By:JavaCC: Do not edit this line. AnalizadorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AnalizadorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int Letra = 5;
  /** RegularExpression Id. */
  int Dig = 6;
  /** RegularExpression Id. */
  int Simbolos = 7;
  /** RegularExpression Id. */
  int Input = 8;
  /** RegularExpression Id. */
  int Disp = 9;
  /** RegularExpression Id. */
  int PalabrasRA = 10;
  /** RegularExpression Id. */
  int PalabrasR = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<Letra>",
    "<Dig>",
    "<Simbolos>",
    "<Input>",
    "<Disp>",
    "<PalabrasRA>",
    "<PalabrasR>",
    "\"=\"",
    "\"(\\\'\"",
    "\"\\\');\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"_\"",
    "\");\"",
    "\"\\\'\"",
    "\"\\\',\"",
  };

}
